# language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t allanshivji/docker-reactrepo -f Dockerfile.dev .
script:
    - docker run -e CI=true allanshivji/docker-reactrepo npm run test
deploy:
    provider: elasticbenstalk
    region: "us-east-2"
    app: "docker-reactrepo"
    env: "DockerReactrepo-env"
    bucket_name: "elasticbeanstalk-us-east-2-287822648138"
    bucket_path: "docker-reactrepo"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY