language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t allanshivji/docker-reactrepo -f Dockerfile.dev .

script:
    - docker run -e CI=true allanshivji/docker-reactrepo npm run test